import org.gradle.api.JavaVersion

object Versions {
    val JVM = JavaVersion.VERSION_17
    const val GRADLE = "8.1.1"
    const val KOTLIN = "1.9.23"
    const val COMPOSE = "1.6.11"
    const val SWIFT_KLIB = "0.5.1"
    const val COMPOSE_ANDROID = "1.5.4"
    const val MOKO_RESOURCES = "0.24.1"
    const val MOKO_GRAPHICS = "0.9.0"
    const val MOKO_PARCELIZE = "0.9.0"
    const val GOOGLE_SIGN_IN_POD = "7.0.0"
    const val DATE_TIME = "0.4.0"
    const val COLLECTIONS = "0.3.7"
    const val STRAPI_KMM = "10.0.103"
    const val KOIN = "3.5.0"
    const val KOIN_COMPOSE = "1.1.0"
    const val VOYAGER = "1.1.0-alpha02"
    const val ACTIVITY_COMPOSE = "1.8.0"
    const val APP_COMPAT = "1.6.1"
    const val CORE_KTS = "1.12.0"
    const val SECURITY_CRYPTO = "1.0.0"
    const val PLAY_SERVICES_AUTH = "20.7.0"
    const val SPLASH_SCREEN = "1.1.0-alpha02"
    const val FIREBASE = "32.7.0"
    const val SERIALIZATION = "1.9.21"
    const val PLAY_SERVICES_PLUGIN = "4.3.14"
    const val CRASHLYTICS_PLUGIN = "2.9.4"
    const val ANDROID_IMAGE_PICKER = "2.1"
    const val LIB_PHONE_NUMBER = "0.1.1-metacto-2"
    const val ANDROID_CROPPER = "4.5.0"
    const val COIL = "3.0.0-alpha02"
    const val COIL_ANDROID = "2.5.0"
    const val COMPOTTIE = "1.1.0"
    const val WEBVIEW = "1.9.12"
    const val EXO_PLAYER = "1.3.1"
    const val GIT_LIVE = "1.10.4"
    const val YOUTUBE_PLAYER = "12.1.0"
    const val SHIMMER = "1.3.1"
}