name: Build & upload the debug package
# Trigger on every tag creation
on:
  push:
    branches:
      - 'new_core'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan/caches
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-macos-*
          key: ${{ runner.os }}-konan-${{ hashFiles('**/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Update local properties
        env:
          PUBLISH_REPO_USER: ${{ secrets.PUBLISH_REPO_USER }}
          PUBLISH_REPO_TOKEN: ${{ secrets.PUBLISH_REPO_TOKEN }}
          PUBLISH_CORE_VERSION: 0.2.${{ github.run_number }}-alpha
        run: echo PUBLISH_REPO_USER=$PUBLISH_REPO_USER$'\n'
          PUBLISH_CORE_VERSION=$PUBLISH_CORE_VERSION$'\n'
          PUBLISH_REPO_TOKEN=$PUBLISH_REPO_TOKEN > ./local.properties

      - name: Print local.properties content
        run: cat ./local.properties

      - name: Update versions properties
        env:
          PUBLISH_CORE_VERSION: 0.2.${{ github.run_number }}-alpha
        run: echo PUBLISH_CORE_VERSION=$PUBLISH_CORE_VERSION> ./versions.properties

      - name: Print versions.properties content
        run: cat ./versions.properties

      - name: Update version catalog
        run: ./gradlew updateVersionCatalog

      - name: Commit updated version catalog
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add gradle/libs.versions.toml
          git commit -m "Update metacto-core version to 0.2.${{ github.run_number }}-alpha"
          git push

      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGithubRepository
